### ISSUE TITLE
dict object has no attribute 'bp'

### ISSUE THREAD

**Issue by cinterloper** [alcarithemad/zfsp#6]
I have been attempting to get this to work with a minimal zpool created clean. 
when I try to run the 'ls' command with the argument -p (pool file) I get an exception on line 26 in datasets.py
        objset_block = self.pool.read_block(self.dsl_dataset.bp)
![debug](https://user-images.githubusercontent.com/1668926/63646105-64fef700-c6fc-11e9-8a7d-7cf23703f69d.png)

**Comment by alcarithemad** [comment]
Probably an unsupported ZFS feature. Those should probably be rejected, or at least produce a warning.

Did you pass `-d` to `zpool create`? That disables all the v5000 features, and you can then enable the supported ones as zpool options. See also `man zpool-features`.

tests/fixtures.sh has some sample pool creation commands.

**Comment by cinterloper** [comment]
I see. creating a pool with `-d` did the trick. Thanks for the response!
